### ISSUE TITLE
Almost done!

### ISSUE THREAD

**Issue by eRicCharlEs** [eRicCharlEs/ticTactoe#2]
BUG: I went ahead and tried to finish this last night. Unfortunately, I was unable to get the gameStatus() function to work correctly. That being said, I set everything up the way the instructions say. The issue is I haven't been able to figure out a good way to determine if the game is a draw. The game will just keep asking for input past 9 moves. With the functions the professor has laid out, I wasn't able to come up with a working solution just yet.

**Comment by iamyuvi** [comment]
i’m on it rn.

**Comment by eRicCharlEs** [comment]
Issue was resolved. Review pull request.
